#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

if len(sys.argv) < 2:
	print "Error: Modem name required!"
	sys.exit(1);

if len(sys.argv) < 3:
	print "Error: Number to dial required!"
	sys.exit(1);

modemName = sys.argv[1]
number = sys.argv[2]

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	print "[ %s ]" % (path)

	if "org.ofono.VoiceCallManager" not in properties["Interfaces"]:
		continue

	if properties["Name"] != modemName:
		continue

	manager = dbus.Interface(bus.get_object('org.ofono', path),
							'org.ofono.VoiceCallManager')

    	path = manager.Dial(number, "")

	print "Originated call [%s]" % (path)


