#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

if len(sys.argv) != 2:
	print "Error: Modem name required!"
	sys.exit(1);

modemName = sys.argv[1]

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
		'org.ofono.Manager')
modems = manager.GetModems()

for path, properties in modems:
	if properties["Name"] != modemName:
		continue

	print "Disconnecting modem %s..." % path
	modem = dbus.Interface(bus.get_object('org.ofono', path),
							'org.ofono.Modem')

	modem.SetProperty("Powered", dbus.Boolean(0))

