#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	print "[ %s ]" % (path)

	if "org.ofono.VoiceCallManager" not in properties["Interfaces"]:
		continue

	mgr = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.VoiceCallManager')

	calls = mgr.GetCalls()

	for path, properties in calls:
		print "    [ %s ]" % (path)

		object = dbus.Interface(bus.get_object('org.ofono', path), 
					'org.ofono.VoiceCall')

		object.Hangup()

		print

print "Hangup Done"
