#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.bluez', '/'),
						'org.bluez.Manager')
props = manager.GetProperties()

for adapter in props["Adapters"]:
	print "%s" % (adapter)
	

