#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.bluez', '/'),
						'org.bluez.Manager')
props = manager.GetProperties()

for path in props["Adapters"]:
	object = dbus.Interface(bus.get_object('org.bluez', path),
							'org.bluez.Adapter')
	props = object.GetProperties()
	devices = props["Devices"]
	for device in devices:
		print device

